### ISSUE TITLE
Bug in escape_string: only the first occurrence of single quotes are escaped

### ISSUE THREAD

**Issue by gaurav** [veg/phylotree.js#106]
The `escape_string(nn)` function escapes single quotes by doubling them:

https://github.com/veg/phylotree.js/blob/35ec8078acb6d31200be2adc72f658521bb1e9cf/src/main.js#L1106-L1110

Unfortunately, [`String.replace` with a string first argument only replaces the first occurrence of the provided string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Parameters). This could be fixed by using regular expressions instead, e.g. `nn.replace(/\'/g, "''")`.

Here's a JSFiddle showing what I mean: https://jsfiddle.net/eywraw8t/422467/

**Comment by spond** [comment]
Dear @gaurav,

Great catch. Looks like @stevenweaver is gonna include the fix in the next release.

Best,
Sergei
