### ISSUE TITLE
Update scale on zoom

### ISSUE THREAD

**Issue by AABoyles** [veg/phylotree.js#111]
When the `show-scale` and `zoom` options are both true, zoom operations don't trigger the scale to update. For panning, that's fine, but zooming in or out causes the scale to become inaccurate.

**Comment by stevenweaver** [comment]
Thank you Tony, 

Version 1.0.0 is under active development right now, so reported issues like these are appreciated. 

Best,
Steven

**Comment by Puneetraj02** [comment]
Any update about this issue

**Comment by jakobtroidl** [comment]
any update?

**Comment by leishenggit** [comment]
any update?

**Comment by stevenweaver** [comment]
Should be resolved in 1.0.4.
