### ISSUE TITLE
MAKE A PHYLIP TO NEWICK CONVERTOR

### ISSUE THREAD

**Issue by aglucaci** [veg/phylotree.js#118]
TOP PRIORITY!!!

**Comment by aglucaci** [comment]
PER THIS SITE: https://www.ncbi.nlm.nih.gov/Taxonomy/CommonTree/wwwcmt.cgi

**Comment by stevenweaver** [comment]
@aglucaci, I've tagged this issue as critical. I should have an implementation within the first two weeks of March.
