### ISSUE TITLE
[1.0.0alpha] node_label

### ISSUE THREAD

**Issue by spond** [veg/phylotree.js#119]
Dear @stevenweaver,

In the current codebase, `node_label` does not have a setter, and cannot be specified using options. The only way to set it is something quite ugly:

```
rendered_tree = {
   
  var t = tree.render("#tree_container", {
  height:height, 
  width:width,
  'left-right-spacing': 'fit-to-size', 
  'top-bottom-spacing': 'fit-to-size',
  'is-radial' : true,
  'node_circle_size' : (n)=>0
});
  /** SET NODE LABEL **/
  t.node_label = n=>"";
                
  t.update();
  return t;
}
```

A preferred mechanism would be something like 

```
 tree.render(...).node_label (n=> ...)
```

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond, 

Thank you for the recommendation. I will include the feature shortly.

Best,
Steven
