### ISSUE TITLE
color branches and annotate internal node with bootstrap values

### ISSUE THREAD

**Issue by jpsglouzon** [veg/phylotree.js#12]
Hi,
Could you provide examples on how to:
 - color branches according to clustering. A clustering is usually in the form of a list of indices which associates to each data a cluster id.     
 - add bootstrap values to internal node; convenient to easily see whether or not a specific subtree is statistically significant.

**Comment by jpsglouzon** [comment]
Also, in wich way is it possible to export the tree in jpeg/png or svg?

**Comment by spond** [comment]
Dear @jpsglouzon,

Sure, I'll make a gist. Can you provide an example Newick tree with clustering annotations, to make sure it works on your data. Or if you have an external annotation file (like .csv), that would work too.

Also, we do have code for exporting the trees, I'll plug it into the example.

Best,
Sergei

**Comment by jpsglouzon** [comment]
This is the csv of the clustering:
PSTVd,TASVd,TCDVd,CSVd,CLVd,CCCvd,ASSVd,PBCVd,CVd-OS,CbVd-1,CbVd-2,CbVd-3,CCHMVd,ELVd,ASBVd,HSVd,CVdIV,CVDIII,CBLVd,CEVd,PLMVd
1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,1,1,1,1,1,2

And the newick tree with bootstrap values:

(((((((TASVd:0.06828169,CSVd:0.06828169)0.8170:0.05635267,CEVd:0.12463435)0.8290:0.06964112,(PSTVd:0.02617095,TCDVd:0.02617095)1.0000:0.16810452)0.6700:0.08751399,CLVd:0.28178947)0.8700:0.13005822,(HSVd:0.26704011,(CCCVd:0.20577326,CVdIV:0.20577326)0.6520:0.06126685)0.8790:0.14480757)0.8810:0.18306776,(((CbVd-2:0.08236826,CbVd-3:0.08236826)0.9300:0.10543001,CbVd-1:0.18779827)0.9970:0.29222981,(PBCVd:0.38569588,(CBLVd:0.30671661,(ASSVd:0.25961362,(CVd-OS:0.14517605,CVDIII:0.14517605)0.9870:0.11443757)0.5950:0.04710299)0.5660:0.07897927)0.7300:0.09433220)0.6860:0.11488736)0.9840:0.46199326,((CCHMVd:0.37098428,PLMVd:0.37098428)0.8850:0.20471288,(ELVd:0.37028264,ASBVd:0.37028264)0.8730:0.20541453)0.9840:0.48121154);

Thanks.

**Comment by spond** [comment]
Dear @jpsglouzon,

Take a look at http://bl.ocks.org/spond/dbc459acfaa6f134c67d 

Sergei

**Comment by jpsglouzon** [comment]
It works like a charm. 

Thank your very much @spond .

**Comment by fasemoreakinyemi** [comment]
@spond what if you do not have a cluster file but you want to get the cluster from the instance of the created tree and subsequently color. or better yet how can you get a cluster file from a created tree
