### ISSUE TITLE
[1.0.0alpha] "draw-size-bubbles" is not functional

### ISSUE THREAD

**Issue by spond** [veg/phylotree.js#121]
Several issues here:

1. Setting 'draw-size-bubbles' in options throws exceptions because of references to non-existent `this.phylotree.node_bubble_size`

2. There is no way to set `node_bubble_size` in the rendered object.

**Comment by stevenweaver** [comment]
Dear @spond, 

Thank you. Some render options, such as `draw-size-bubbles`, hasn't been ported over quite yet. 

Best,
Steven

**Comment by spond** [comment]
Dear @stevenweaver,

That's to be expected. I can use ugly hacks to get them working now, but would be nice to have all render features working at some point soon.

Best,
Sergei
