### ISSUE TITLE
Leaf node selections

### ISSUE THREAD

**Issue by lubwen** [veg/phylotree.js#124]
Hi Guys,

I am sorry that I have to bug you guys probably a few more times until I get the final product.

For my project, I need to be able to easily highlight selected leaf nodes and copy out the names of the selected leaf nodes. I am attaching a picture showing what I want:

![image](https://user-images.githubusercontent.com/26776983/64650430-0613d000-d3d4-11e9-8720-95f153963e01.png)

I am thinking about using the 'custom menu items' method (see link below) to allow me to select/deselect a leaf node. Could you guys advise whether this is a feasible approach? Or I should use a better/different appoach? 

http://phylotree.hyphy.org/examples/custom-menu-items/

I can achieve the same functionality using cytoscape.js, using 'Ctrl-Click' or 'Shift-Click'. Thus I am wondering whether we have similar functionalities for phylotree.js.

Thanks a lot. 
Wen

**Comment by stephenshank** [comment]
Dear @lubwen,

You can select leaves by clicking on the leaf name, then clicking on the "Incident branch" menu option. Alternatively, you can click on the branch that has the desired leaf as a terminal node. This should be enabled by default (you can verify this behavior on the [hello world](http://phylotree.hyphy.org/examples/hello-world/) example).

The [get_selection](http://phylotree.hyphy.org/documentation/selection.html?highlight=get_selection#phylotree.get_selection) method of a `phylotree` object will return all currently selected nodes. Alternatively, if you'd prefer it dynamically updates as selections are made, you can use the [selection_callback](http://phylotree.hyphy.org/documentation/selection.html?highlight=selection_callback#phylotree.selection_callback) method. This function will be called every time a selection is made.

Please let me know if you have any additional questions.

Best,
Stephen

**Comment by lubwen** [comment]
Dear @stephenshank,

Thanks a lot for providing this nice answer. I was able to get it to work!

Best regards,

Wen
