### ISSUE TITLE
Leaf Node Labeling

### ISSUE THREAD

**Issue by lubwen** [veg/phylotree.js#125]
Dear All,

I am storing information in the 'node-name' section of the Newick file, such as compound name and compound structure. When I displayed the tree, all information in the 'node-name' was shown.

I would like to display just the compound name, see the image below. Could I ask how you guys would advise me to achieve this?

![image](https://user-images.githubusercontent.com/26776983/64997071-7fa83400-d894-11e9-9053-6faa4c1d71b7.png)

Any suggestions will be appreciated. Thank you very much.

Best regards,

Wen

**Comment by stephenshank** [comment]
Dear @lubwen,

You can use the [get_nodes](http://phylotree.hyphy.org/documentation/nodes_branches.html?highlight=get_nodes#phylotree.get_nodes) function for this.

After passing in the newick string, but before calling `layout`, you can do something like

```
tree.get_nodes().forEach(function(node) {
  if(node.name) {
    node.name = node.name.split('@')[0];
  }
});
```

Please let me know if encounter any issues.

Best,
Stephen

**Comment by lubwen** [comment]
Dear @stephenshank,

Thanks so much! This works nicely!

Best regards,

Wen
