### ISSUE TITLE
Problem displaying some trees for no apparent reason

### ISSUE THREAD

**Issue by juanjo75es** [veg/phylotree.js#126]
Hi, I am having some problems displaying some trees. These trees work in other tree visualization tools but not with phylotree.js. Even the same tree but modifying some ids works in phylotree.js. But I can't identify what I need to modify.

For example, this tree fails with error

> Uncaught TypeError: Cannot read property 'notshown' of undefined
>     at o (phylotree.js:9)
>     at d (phylotree.js:9)
>     at Function.et.placenodes (phylotree.js:9)
>     at et (phylotree.js:9)
>     at fromweb.dna.common.align.html:248

> (((((>_XP_018293900.1_hypothetical_protein_PHYBLDRAFT_123266__Phycomyces_blakesleeanus_NRRL_1555_-__:1503,(>vase_tunicate_XP_002130696.1_peroxisomal_targeting_signal_1_receptor__Ciona_intestinalis_:1003,(>_XP_025081216.1_peroxisomal_targeting_signal_1_receptor-like__Pomacea_canaliculata_:489,>owl_limpet_XP_009057994.1_hypothetical_protein_LOTGIDRAFT_209637__Lottia_gigantea_:491):1002):1485):1832,(((>bark_scorpion_XP_023226490.1_peroxisomal_targeting_signal_1_receptor-like__Centruroides_sculpturatus_:739,>California_sea_hare_XP_012946150.1_PREDICTED__peroxisomal_targeting_signal_1_receptor-like__Aplysia_californica_:736):1254,((>common_house_spider_XP_015914804.1_peroxisomal_targeting_signal_1_receptor_isoform_X3__Parasteatoda_tepidariorum_:63,(>common_house_spider_XP_015914803.1_peroxisomal_targeting_signal_1_receptor_isoform_X2__Parasteatoda_tepidariorum_:14,>common_house_spider_XP_015914800.1_peroxisomal_targeting_signal_1_receptor_isoform_X1__Parasteatoda_tepidariorum_:14):66):828,(>_XP_023708908.1_peroxisomal_targeting_signal_1_receptor__Cryptotermes_secundus_:121,>_XP_021935209.1_peroxisomal_targeting_signal_1_receptor_isoform_X2__Zootermopsis_nevadensis_:121):837):1253):1609,(((>Florida_lancelet_XP_002586247.1_hypothetical_protein_BRAFLDRAFT_62718__Branchiostoma_floridae_:295,(>Belcher's_lancelet_XP_019637889.1_PREDICTED__peroxisomal_targeting_signal_1_receptor-like__Branchiostoma_belcheri_:113,>Florida_lancelet_XP_002610911.1_hypothetical_protein_BRAFLDRAFT_60314__Branchiostoma_floridae_:119):293):876,(>Egyptian_rousette_XP_016018336.1_PREDICTED__peroxisomal_biogenesis_factor_5_isoform_X3__Rousettus_aegyptiacus_:415,((>Gharial_XP_019382988.1_PREDICTED__peroxisomal_biogenesis_factor_5_isoform_X2__Gavialis_gangeticus_:18,>Australian_saltwater_crocodile_XP_019404418.1_PREDICTED__peroxisomal_biogenesis_factor_5_isoform_X2__Crocodylus_porosus_:18):281,(>chicken_NP_001012836.1_peroxisomal_targeting_signal_1_receptor__Gallus_gallus_:96,>emu_XP_025969087.1_peroxisomal_biogenesis_factor_5_isoform_X1__Dromaius_novaehollandiae_:96):285):407):876):1334,((>purple_sea_urchin_XP_011683182.1_PREDICTED__LOW_QUALITY_PROTEIN__peroxisomal_targeting_signal_1_receptor__Strongylocentrotus_purpuratus_:598,>_XP_006819303.1_PREDICTED__peroxisomal_targeting_signal_1_receptor-like__Saccoglossus_kowalevskii_:590):1081,((>_XP_013412121.1_peroxisomal_targeting_signal_1_receptor_isoform_X5__Lingula_anatina_:228,((>_XP_013412118.1_peroxisomal_targeting_signal_1_receptor_isoform_X3__Lingula_anatina_:25,>_XP_013412119.1_peroxisomal_targeting_signal_1_receptor_isoform_X4__Lingula_anatina_:15):82,(>_XP_013412117.1_peroxisomal_targeting_signal_1_receptor_isoform_X2__Lingula_anatina_:15,>_XP_013412116.1_peroxisomal_targeting_signal_1_receptor_isoform_X1__Lingula_anatina_:25):82):221):771,((>Yesso_scallop_XP_021372599.1_peroxisomal_targeting_signal_1_receptor-like_isoform_X1__Mizuhopecten_yessoensis_:120,>Yesso_scallop_XP_021372600.1_peroxisomal_targeting_signal_1_receptor-like_isoform_X2__Mizuhopecten_yessoensis_:120):410,((>Pacific_oyster_XP_011431302.1_PREDICTED__peroxisomal_targeting_signal_1_receptor_isoform_X2__Crassostrea_gigas_:56,(>eastern_oyster_XP_022341178.1_peroxisomal_targeting_signal_1_receptor-like_isoform_X2__Crassostrea_virginica_:1,>eastern_oyster_XP_022340753.1_peroxisomal_targeting_signal_1_receptor-like_isoform_X2__Crassostrea_virginica_:1):56):175,(>Pacific_oyster_XP_011431301.1_PREDICTED__peroxisomal_targeting_signal_1_receptor_isoform_X1__Crassostrea_gigas_:62,(>eastern_oyster_XP_022341176.1_peroxisomal_targeting_signal_1_receptor-like_isoform_X1__Crassostrea_virginica_:1,>eastern_oyster_XP_022340751.1_peroxisomal_targeting_signal_1_receptor-like_isoform_X1__Crassostrea_virginica_:1):62):178):410):768):1080):1334):1609):1832):2189,((>_XP_002113707.1_hypothetical_protein_TRIADDRAFT_57411__Trichoplax_adhaerens_:1136,(>cat_flea_XP_026476292.1_peroxisomal_targeting_signal_1_receptor-like__Ctenocephalides_felis_:4,>cat_flea_XP_026476268.1_peroxisomal_targeting_signal_1_receptor-like__Ctenocephalides_felis_:4):1151):1965,((>_XP_009521756.1_hypothetical_protein_PHYSODRAFT_556029__Phytophthora_sojae_:816,(>_XP_008874240.1_hypothetical_protein__variant__Aphanomyces_invadans_:19,>_XP_008874239.1_hypothetical_protein_H310_09842__Aphanomyces_invadans_:19):816):1602,(>_XP_012753205.1_hypothetical_protein_SAMD00019534_073440__partial__Acytostelium_subglobosum_LB1_:1024,(>_XP_003287008.1_hypothetical_protein_DICPUDRAFT_47119__Dictyostelium_purpureum_:386,>_XP_637903.1_tetratricopeptide-like_helical_domain-containing_protein__Dictyostelium_discoideum_AX4_:386):1020):1603):1962):2189):2645,((>_XP_020429032.1_tetratricopeptide-like_helical_domain-containing_protein__Heterostelium_album_PN500_:1400,(>_XP_004360557.1_tetratricopeptide-like_helical_domain-containing_protein__Cavenderia_fasciculata_:797,>_XP_012752635.1_hypothetical_protein_SAMD00019534_074840__Acytostelium_subglobosum_LB1_:800):1385):2357,(((((>foxtail_millet_XP_004973818.1_peroxisome_biogenesis_protein_5_isoform_X1__Setaria_italica_:29,>_XP_025820202.1_peroxisome_biogenesis_protein_5_isoform_X1__Panicum_hallii_:29):180,((>_NP_001130381.1_uncharacterized_protein_LOC100191477__Zea_mays_:9,>_XP_008666974.1_uncharacterized_protein_LOC100191477_isoform_X1__Zea_mays_:9):112,(>_XP_008679526.1_peroxisome_biogenesis_protein_5_isoform_X1__Zea_mays_:67,>sorghum_XP_002445936.1_peroxisome_biogenesis_protein_5_isoform_X1__Sorghum_bicolor_:67):101):169):486,((>Japanese_rice_XP_015650439.1_peroxisome_biogenesis_protein_5_isoform_X1__Oryza_sativa_Japonica_Group_:82,(>malo_sina_XP_006659547.1_PREDICTED__peroxisome_biogenesis_protein_5_isoform_X1__Oryza_brachyantha_:40,>Japanese_rice_XP_015650440.1_peroxisome_biogenesis_protein_5_isoform_X2__Oryza_sativa_Japonica_Group_:40):82):345,(>_XP_020164686.1_peroxisome_biogenesis_protein_5_isoform_X1__Aegilops_tauschii_subsp._tauschii_:159,>stiff_brome_XP_003574713.1_peroxisome_biogenesis_protein_5_isoform_X1__Brachypodium_distachyon_:156):340):487):1131,((>_XP_023740607.1_peroxisome_biogenesis_protein_5__Lactuca_sativa_:537,((>_XP_027170576.1_peroxisome_biogenesis_protein_5__Coffea_eugenioides_:11,(>coffee_XP_027064007.1_LOW_QUALITY_PROTEIN__peroxisome_biogenesis_protein_5-like__Coffea_arabica_:9,>coffee_XP_027061605.1_peroxisome_biogenesis_protein_5-like__Coffea_arabica_:9):9):326,(>potato_XP_006352575.1_PREDICTED__peroxisome_biogenesis_protein_5__Solanum_tuberosum_:76,>common_tobacco_NP_001313017.1_peroxisome_biogenesis_protein_5-like__Nicotiana_tabacum_:76):318):506):804,((>_XP_010539369.1_PREDICTED__peroxisome_biogenesis_protein_5_isoform_X1__Tarenaya_hassleriana_:243,(>_XP_023639322.1_peroxisome_biogenesis_protein_5__Capsella_rubella_:117,(>radish_XP_018476760.1_PREDICTED__peroxisome_biogenesis_protein_5__Raphanus_sativus_:31,(>rape_NP_001303172.1_peroxisome_biogenesis_protein_5-like__Brassica_napus_:18,(>_XP_013629715.1_PREDICTED__peroxisome_biogenesis_protein_5-like__Brassica_oleracea_var._oleracea_:8,>field_mustard_XP_009132316.1_PREDICTED__peroxisome_biogenesis_protein_5-like__Brassica_rapa_:8):18):28):117):234):630,((>sesame_XP_011095665.1_peroxisome_biogenesis_protein_5__Sesamum_indicum_:145,>spotted_monkey_flower_XP_012848952.1_PREDICTED__peroxisome_biogenesis_protein_5__Erythranthe_guttata_:145):370,(>_XP_022892219.1_peroxisome_biogenesis_protein_5__Olea_europaea_var._sylvestris_:243,>Japanese_morning_glory_XP_019185113.1_PREDICTED__peroxisome_biogenesis_protein_5__Ipomoea_nil_:238):371):628):797):1102):1492,(((>_XP_020999325.1_peroxisome_biogenesis_protein_5_isoform_X2__Arachis_duranensis_:8,>peanut_XP_025657209.1_peroxisome_biogenesis_protein_5_isoform_X2__Arachis_hypogaea_:8):846,((>cassava_XP_021612634.1_peroxisome_biogenesis_protein_5-like__Manihot_esculenta_:312,(>sweet_orange_XP_006474746.1_peroxisome_biogenesis_protein_5__Citrus_sinensis_:10,>_XP_006452789.1_peroxisome_biogenesis_protein_5__Citrus_clementina_:10):309):545,(>_XP_023918190.1_peroxisome_biogenesis_protein_5__Quercus_suber_:350,>_XP_015881476.1_peroxisome_biogenesis_protein_5__Ziziphus_jujuba_:354):545):830):1234,(((>cacao_XP_007020294.2_PREDICTED__peroxisome_biogenesis_protein_5_isoform_X2__Theobroma_cacao_:274,(>_XP_017647541.1_PREDICTED__peroxisome_biogenesis_protein_5_isoform_X1__Gossypium_arboreum_:164,(>_XP_021288868.1_peroxisome_biogenesis_protein_5_isoform_X1__Herrania_umbratica_:69,>cacao_XP_007020291.2_PREDICTED__peroxisome_biogenesis_protein_5_isoform_X1__Theobroma_cacao_:69):161):265):658,((>_XP_015967867.1_peroxisome_biogenesis_protein_5_isoform_X1__Arachis_duranensis_:4,>_XP_016204536.1_peroxisome_biogenesis_protein_5__Arachis_ipaensis_:4):416,(>Euphrates_poplar_XP_011000400.1_PREDICTED__peroxisome_biogenesis_protein_5__Populus_euphratica_:126,(>black_cottonwood_XP_024449400.1_peroxisome_biogenesis_protein_5_isoform_X2__Populus_trichocarpa_:6,>black_cottonwood_XP_024449399.1_peroxisome_biogenesis_protein_5_isoform_X1__Populus_trichocarpa_:6):129):402):642):1050,((>_XP_010676141.1_PREDICTED__peroxisome_biogenesis_protein_5__Beta_vulgaris_subsp._vulgaris_:271,(>spinach_XP_021841898.1_peroxisome_biogenesis_protein_5__Spinacia_oleracea_:157,(>quinoa_XP_021735517.1_peroxisome_biogenesis_protein_5-like__Chenopodium_quinoa_:19,>quinoa_XP_021774032.1_peroxisome_biogenesis_protein_5-like__Chenopodium_quinoa_:19):158):244):742,(>date_palm_XP_008806178.1_peroxisome_biogenesis_protein_5-like__Phoenix_dactylifera_:349,(>_XP_020583949.1_peroxisome_biogenesis_protein_5__Phalaenopsis_equestris_:114,>_XP_020690982.1_peroxisome_biogenesis_protein_5__Dendrobium_catenatum_:114):336):759):1015):1236):1477):2374):2645):2888,((>_XP_004344039.1_tetratricopeptide_repeat-containing_protein__Acanthamoeba_castellanii_str._Neff_:1394,(>_5-3:361,>_5-2:361):1394):2888,(>_XP_004344040.1_hypothetical_protein_ACA1_053810__Acanthamoeba_castellanii_str._Neff_:2210,(>_5-1:1583,(>Pacific_oyster_XP_011431303.1_PREDICTED__peroxisomal_targeting_signal_1_receptor__Crassostrea_gigas_:823,>_XP_005826999.1_hypothetical_protein_GUITHDRAFT_114013__Guillardia_theta_CCMP2712_:823):1583):2210):2888):2888);

Would like to know what is wrong with this tree or how to fix that behaviour.

**Comment by spond** [comment]
Dear @juanjo75es,

You have a quote character (`'`) in a sequence name (`>Belcher's_lancelet_XP_019637889.1_PREDICTED__peroxisomal_targeting_signal_...`)

Because spaces are not interpreted as parts of sequence names per Newick specification, phylotree.js uses 

```
'sequence name' 

or 

"sequence name"
```

to allow those. If you have an apostrophe in one of the words, it will be interpreted as an unterminated sequence name. The solution is to either delete the `'` or quote the entire taxon name using "name" or 'name' (in the latter case you can use '' to include an apostrophe).


Best,
Sergei

**Comment by juanjo75es** [comment]
Yep. Thanks.
