### ISSUE TITLE
Displaying leaf node data

### ISSUE THREAD

**Issue by lubwen** [veg/phylotree.js#127]
Hi All,

I have some compound inhibition data that I would like to display in my phylotree. The inhibition data (a number ranging from 0 to 100) will be stored in the leaf node. What I would like to achieve is a graphic that will look like the one below: 

![image](https://user-images.githubusercontent.com/26776983/65728428-c6a1e080-e06f-11e9-8afc-2a313c8d6b10.png)

where the color rectangles on the right indicate the inhibitions.

I am trying to borrow the code from the 'leafdata' example:
http://phylotree.hyphy.org/examples/leafdata/

However, I was not able to render any 'rectangles'. See my code here (line #292 to line #298):
http://lubw.com/phylotree/mod.php

What am I doing wrong here? Is 'leafdata' the right example to copy from? Does anyone of you have a better recommendation to achieve this?

Thanks a lot. Any suggestions will be highly appreciated.

Best regards,

Wen

**Comment by stephenshank** [comment]
Dear @lubwen,

This is an issue with how you are using d3, not with phylotree. You are calling `data` on a number, whereas it expects an array. Adjusting the corresponding line in the `style_nodes` function to

```
var annotation = element.selectAll ("rect").data ([30]);
```

(note the square brackets around 30) will get some rectangles to appear.

Note that d3 also has [datum](https://github.com/d3/d3-selection/blob/v1.4.0/README.md#selection_datum) for individual data values.

Best,
Stephen

**Comment by lubwen** [comment]
Dear @stephenshank,
Thanks a lot. Best regards,
Wen
