### ISSUE TITLE
Get information from last selected leaf node

### ISSUE THREAD

**Issue by lubwen** [veg/phylotree.js#128]
Hi All,

For my application, I would like to be able to get information from the most recently selected leaf node. Is there a function to achieve this?

I understand that I can use 'get_selection' or 'selection_callback' to get the list of all selected nodes. But it appears that I could not use either of these two functions to achieve my goal.

Any suggestions will be highly appreciated.

Thanks a lot. Best regards,

Wen

**Comment by stephenshank** [comment]
Dear @lubwen,

This is an interesting use case, and is not directly supported by the API at the moment.

However, it does seem possible to hack this together with the existing API and some JavaScript. Using `selection_callback`, you can try writing the selection to a variable, and when a new selection is made, comparing the new one with the old one to determine what was added.

I'm not entirely sure what you intend, so it's tough to determine new functionality for the API, or how it ought to work to support other, related use cases. For instance, entire clades may be selected, as well as all leaves/internal nodes.

Best,
Stephen

**Comment by lubwen** [comment]
Dear @stephenshank,

I figured this out. This can be implemented from within the 'style_nodes' method using element.on('click', function() {...}).

Thanks.

Best, 
Wen
