### ISSUE TITLE
Dysfunctional spacing_x and spacing_y methods 

### ISSUE THREAD

**Issue by stevenweaver** [veg/phylotree.js#13]
The methods `spacing_x` and `spacing_y` do not make an impact on visual branch expansion or contraction of the phylotree.

To reproduce : 
- Visit http://veg.github.io/hyphy-vision/absrel/
- Click on the button that is fashioned with a `fa-arrows-h` emblem
- Notice no expansion

**Comment by talnagar** [comment]
Hi
I ran into this issue myself and now I see it's an open bug.
Is there a way to zoom in on the tree in a different way?
thank you!
Tal
