### ISSUE TITLE
Rerooting in 1.0.0-alpha

### ISSUE THREAD

**Issue by sdwfrost** [veg/phylotree.js#132]
I like the (new?) v1 API, but I've been having problems with porting over the old examples. How can I reroot a tree with the location generated by compute_midpoint (as it doesn't return a node)? The code at [https://github.com/veg/phylotree.js/blob/1.0.0-alpha/src/rooting.js](https://github.com/veg/phylotree.js/blob/1.0.0-alpha/src/rooting.js) suggests that this isn't supported yet?

**Comment by stevenweaver** [comment]
Dear @sdwfrost, 

v1 hasn't been fully ported over yet. I'm currently in the middle of two paper pushes, so my response time to implement feature requests might be a bit slow at the moment. v1 only needs a bit more polish before release and it is highly desired, so I'll chat with the lab here to see when we can address these issues as soon as possible.

Best,
Steven

**Comment by stevenweaver** [comment]
This should now be fixed. Sorry for the delay here.
