### ISSUE TITLE
Grabbing node names for collapse_node in 1.0.0-alpha.21

### ISSUE THREAD

**Issue by droush** [veg/phylotree.js#154]
Hello!

I am trying to implement Phylotree into a Vue app. I've run into trouble trying to utilize the collapse_node() function to try to programmatically collapse nodes (if this is even possible currently) on the tree to make it more manageable for the user (the tree has 1500+ leaves). I cannot seem to get the correct input for the function. I've ran the get_nodes() and it returns an object but I can't seem to find any identifiers for the nodes to use as input. 

I am not that familiar with javascript, so this may be something simple I am missing so my apologies. 

I based my implementation off the examples given in #129.

`    generateTree () {

      var tree = new phylotree(cydrasilTree)

      let height = 15000
      let width = 1600
      let svg = document.createElement('div')
      svg.setAttribute('id', 'tree_display')
      document.body.appendChild(svg)

      var renderedTree = tree.render('#tree_display', {
        height: height,
        'show-scale': false,
        compression: 0.5,
        width: width,
        'left-right-spacing': 'fit-to-size',
        'top-bottom-spacing': 'fit-to-size',
      })`

Thank you for your help!
Daniel

**Comment by spond** [comment]
Dear @droush,

I have some example code for doing this in https://observablehq.com/@spond/sd-pirc-sequence-qa where you collapse everything except the clades that have "tagged" nodes.

The relevant code fragment (which is "hackish") is the following. You can traverse the tree and "tag" the nodes with `n.collapsed`. 

Best,
Sergei

```
t.traverse_and_compute ((n) => {
      if (!d3.layout.phylotree.is_leafnode (n)) {
         if ("collapsed" in n) {
            delete n["collapsed"]; 
         }
         n.tagged_view = false;
      }
   });
          
   t.traverse_and_compute ((n) => {
      if (highlight_color (n)) {
        n.tagged_view = true;
      }
      if (n.tagged_view && n.parent) {
        n.parent.tagged_view = true; 
      }
   });
          
   t.traverse_and_compute ((n) => {
      if (!d3.layout.phylotree.is_leafnode (n) && !n.tagged_view && n.parent && n.parent.tagged_view) {
          //console.log (n);
          n.collapsed = true; 
      }
   });
          
   t.placenodes().layout();
```
