### ISSUE TITLE
resize the tree dynamically and line representing the distance too big with 'fit-to-size'

### ISSUE THREAD

**Issue by jpsglouzon** [veg/phylotree.js#16]
Dear @spond,

Is there a way to auto resize the tree according to the size of the container?
Also the line representing the distance between nodes becomes too big with 'fit-to-size' option.

Thanks for your help

**Comment by stevenweaver** [comment]
Dear @jpsglouzon, 

I'm going to close to this issue due to possibility that it is stale. Could you please see https://beta.observablehq.com/@stevenweaver/displaying-phylogenetic-trees-with-phylotree-js and notice how I'm setting width and height for the tree?

Best,
Steven
