### ISSUE TITLE
dependency error in 1.0.0.alpha.25

### ISSUE THREAD

**Issue by amanpatel** [veg/phylotree.js#163]
Just installed 1.0.0.alpha.25 (i was on 16 before). And now I see this error in my build.

``` ERROR  Failed to compile with 1 errors                                                                   7:49:42 PM

This dependency was not found:

* phylotree/build/phylotree.css in ./src/main.js

To install it, you can run: npm install --save phylotree/build/phylotree.css
```

I feel this is probably due to my import 'phylotree' using `./src/main.js` instead of the version in `dist/`. What can be done to fix this?

Also a side question. Is it possible to rename branch names using the branch_name accessor. I tried this in alpha.16 and the branch accessor is never called.

**Comment by amanpatel** [comment]
Nevermind this question. I've fixed the issue. I'm on alpha.22. Instead of using branch_name, I just resorted to using traverse_and_compute and dynamically updating each node's name property. Not ideal but it worked for me.

As a side note what is the state of the examples in 1.0.0.alpha releases? The current examples seem to be calling functions that don't exists anymore.

**Comment by stevenweaver** [comment]
Thank you @amanpatel,

Examples can be found here -- https://observablehq.com/collection/@stevenweaver/phylotree-utilities. 

Sorry for the delay.
