### ISSUE TITLE
FastTree output does not fit to phylotree.js

### ISSUE THREAD

**Issue by longing247** [veg/phylotree.js#18]
First of all, I would like thank you guys for contributing to this project. 

When I tried to feed Phylotree.js with the following input (FastTree output) using the template http://bl.ocks.org/spond/f6b51aa6f34561f7006f, I could not get a desired tree visualization ( issues with scaling?).  
.nwk 
(BRAOA12048:0.00054,BRANA02666:0.00991,((BRAJU21777:0.03087,(ARATH07668:0.01134,ARALY20685:0.03085)1.000:0.13667)0.926:0.02726,(BRANA29265:0.00325,(BRAJU98226:0.00055,BRARP02331:0.00055)0.882:0.00661)0.956:0.01496)0.809:0.00513);

As there is no error messages pop up from the browser console it is very different for me to debug it.

While I copy it to  [Trex Newick Viewer](http://www.trex.uqam.ca/index.php?action=newick), it works fine.

Could you help me? I am looking forward to hearing from you.

Kind regards,

Jiao

**Comment by spond** [comment]
Dear @longing247,

Exactly what kind of issues are you having? Your example renders fine with stock options (http://veg.github.io/phylotree.js/index.html):

![screen shot 2016-04-28 at 9 56 24 am](https://cloud.githubusercontent.com/assets/1018513/14894234/7d51d30a-0d27-11e6-9f0f-025f81649721.png)

Best,
Sergei

**Comment by longing247** [comment]
Dear @spond,

Thanks for your reply.

Compare to the phylotree which was built using the input data given below, the scaling and spatial layout of the tree seem to be problematic. Is this because less nodes were given in the previous dataset?

`((BRADI01293:0.12614,((ORYBR15614:0.04548,(ORYPU16440:0.02805,(ORYRU19525:0.0,ORYSI18955:0.0):0.02011)0.865:0.02201)1.000:0.12358,(((ORYBR15928:0.08268,(ORYPU16760:0.00884,(ORYGL15075:0.00055,((ORYSJ17781:0.01580,ORYRU19909:0.00055)0.846:0.00260,(ORYSI19347:0.00055,ORYNI19717:0.00055)0.782:0.00055)0.938:0.01124)0.987:0.03481)0.872:0.06098)1.000:0.84366,(ORYBR15617:0.16361,(ORYPU16442:0.07001,(ORYSJ17447:0.03634,(ORYRU19527:0.07305,ORYSI18958:0.00054)0.889:0.01409)0.996:0.10872)0.963:0.06920)0.999:0.23021)0.113:0.04987,((TRIUA16048:0.07507,(AEGTA15220:0.12642,AEGTA15221:0.20704)0.710:0.05009)1.000:0.33080,BRADI01292:0.21054)0.830:0.04318)0.892:0.04567)0.953:0.05830)0.986:0.07343,WHEAT88677:0.01379,(TRIUA11819:0.04589,(TRITU12319:0.02842,(WHEAT29025:0.02157,TRITU08224:0.00633)0.857:0.01153)0.976:0.01961)0.688:0.00243);`

![phylotree](https://cloud.githubusercontent.com/assets/78259/14910701/2c3327fc-0df0-11e6-8c8a-445fc6ce08d0.png)
