### ISSUE TITLE
Multiple styles on node name

### ISSUE THREAD

**Issue by talnagar** [veg/phylotree.js#19]
Hello
I would like to display a node label that contains a text with several colors/styles. 
Is it possible to do it?
thank you

**Comment by stevenweaver** [comment]
Hello @talnagar, 

Yes, you can style nodes however you like using the `style_nodes` method.
Please view an example I created for you [here](http://bl.ocks.org/stevenweaver/402f8faa2abd1bd8cf9844cc2a1b32c2)

Best,
Steven

**Comment by talnagar** [comment]
Hello Steven,
Thank you!
It was a great help!
Best,
Tal
