### ISSUE TITLE
Error in hello world html?

### ISSUE THREAD

**Issue by Georgva** [veg/phylotree.js#199]
Hi there, I am currently trying to get phylotree.js running but am already stumbling over the example html files. I am a complete newbie in html but the slash in the <svg if="tree_display" **/**> seems odd to me. I don't think you need the whole code beccause it is in the git repo. But when I try to run the hello world html, my output in the browser is shown in the picture. (It's not what it should be..) I really hope someone could help me out. Thank a lot in advance!
(I don't even know if here is the correct place to ask this question so if not, where should I post thihs question?)
Georg
![output_phylotreejs](https://user-images.githubusercontent.com/42862368/86511560-b71fa700-bdfa-11ea-8fcc-71cda2f6f00c.png)

**Comment by gaurav** [comment]
Hi Georg! The slash is totally fine -- it tells HTML that no end tag is needed there (i.e. `<svg if="tree_display" />` is identical to `<svg if="tree_display"></svg>`).

I think I see where the problem is in the example file. Could you please try saving [my fork on the example file](https://raw.githubusercontent.com/gaurav/phylotree.js/1bcd71476322e429e01c33f0bc6496e19cdb558a/examples/hello-world/index.html) to your computer and opening it from there, and letting me know if that works? You can see the changes I've made in [my pull request](https://github.com/veg/phylotree.js/pull/200/files).

**Comment by Georgva** [comment]
Oh nice, this worked! I thought I have checked all of the dependencies but I might have forgotten one, thanks! 
As now the normal trees can be shown, unfortunately I can not display any tree which was read in from a nwk file... Is there a hack equally simple as the one before to solve the problem? I have the yokoyama file included in the folder of the html file (vanilla example). But I again only get the code as output. See my code:
`<!DOCTYPE html>
<html lang='en'>

<head>
  <meta charset="utf-8">

  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <link href="https://veg.github.io/phylotree.js/phylotree.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  <script src="https://code.jquery.com/jquery.js"></script>
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://d3js.org/d3.v3.min.js"></script>
  <script src="https://veg.github.io/phylotree.js/phylotree.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js" charset="utf-8"></script>

  <style>
#code {
  display: inline-block;
  width: 700px;
  padding-left: 50px;
}
  </style>
</head>
</head>

<body>
  <svg id="tree_display"></svg>
  <div id="code"><pre><code class="javascript">
  d3.text("yokoyama.nwk", function(error, newick) {
  var height = 400,
    width = 400,

    tree = d3.layout.phylotree()
    .svg(d3.select("#tree_display"))
    .options({
      'left-right-spacing': 'fit-to-size',
      // fit to given size top-to-bottom
      'top-bottom-spacing': 'fit-to-size',
      // fit to given size left-to-right
      'selectable': false,
      // make nodes and branches not selectable
      'collapsible': false,
      // turn off the menu on internal nodes
      'transitions': false
      // turn off d3 animations
    })
    .size([height, width])
    .node_circle_size(0); // do not show "circles" at internal nodes

  tree(newick)
    // parse the Newick into a d3 hierarchy object with additional fields
    // generate node coordinates
    .layout();
  // render the tree

});</code></pre></div>

  <script>
    d3.text("yokoyama.nwk", function(error, newick) {
      var height = 400,
        width = 400,

        tree = d3.layout.phylotree()
        .svg(d3.select("#tree_display"))
        .options({
          'left-right-spacing': 'fit-to-size',
          // fit to given size top-to-bottom
          'top-bottom-spacing': 'fit-to-size',
          // fit to given size left-to-right
          'selectable': false,
          // make nodes and branches not selectable
          'collapsible': false,
          // turn off the menu on internal nodes
          'transitions': false
          // turn off d3 animations
        })
        .size([height, width])
        .node_circle_size(0); // do not show "circles" at internal nodes

      tree(newick)
        // parse the Newick into a d3 hierarchy object with additional fields
        // generate node coordinates
        .layout();
      // render the tree

    });

    // for syntax highlighting
    hljs.initHighlightingOnLoad();
  </script>

</body>

</html>
`

**Comment by gaurav** [comment]
I'll try to have another look at your code tomorrow, but I'd start by checking whether the `error` argument is set, i.e. add
```
if (error) alert("Could not load yokoyama.nwk: " + error);
```

before the line `tree = d3.layout.phylotree()`. That way, if there was any problem in reading the Newick file, your program would warn you about that. You could also use:
```
console.log("Loaded newick: ", newick);
```

To ensure that the Newick string have been loaded correctly.

**Comment by Georgva** [comment]
I included them both, first one after the other and then both at the same time but somehow it does not display any error message.
