### ISSUE TITLE
Modify the context menu

### ISSUE THREAD

**Issue by talnagar** [veg/phylotree.js#20]
Hi
I was wondering if there is a way to modify the context menu shown when clicking on nodes/edges.
Currently I managed doing it when using some naive d3 manipulation: 
`d3.select("#d3_layout_phylotree_context_menu").append('li').text('test').attr('id','testid')`
However, in this way every time the menu is hidden the additions disappear as well and I need to re apply them every time the menu becomes available.

Help will be much appreciated.
Best
Tal

**Comment by spond** [comment]
Dear @talnagar,

Please see http://bl.ocks.org/spond/30926a292ac4f49e1c6c7d900be65f94 

The interface isn't the most flexible (i.e., you are not allowed to directly modify DOM objects in callbacks), but it allows the module to control when updates happen and what takes precedence. 

Cheers,
Sergei

**Comment by talnagar** [comment]
Thank you Sergei! this is the guidance I needed. 
Best,
Tal
