### ISSUE TITLE
Reverse the Tree?

### ISSUE THREAD

**Issue by hannah-fisher** [veg/phylotree.js#204]
Hi, I was wondering if it is possible to reverse/flip the tree? The tree normally has its root on the left side of the page, and its leaves on the right side. Is there any way for me to display my tree with the root on the right and the leaves on the left? Thank you.

**Comment by stephenshank** [comment]
Dear @hannah-fisher,

Which version of phylotree are you using?

v0.x contains a [tanglegram example](http://phylotree.hyphy.org/examples/siv/) that utilizes the feature you describe; see [this line](https://github.com/veg/phylotree.js/blob/master/examples/siv/index.html#L297).

v1.x is still in alpha, and I'd have to check if this feature has been ported over yet.

Best,
Stephen

**Comment by hannah-fisher** [comment]
Thank you so much! I'm not sure which version I'm using...? but I just added that option from the line you linked to and it works for me.
