### ISSUE TITLE
Callback when layout is done

### ISSUE THREAD

**Issue by talnagar** [veg/phylotree.js#21]
Hi 
I was wondering if there is a callback option for tree.layout() or tree.update() ? 
I am trying to add some function that use the tree's nodes coordinates so I have to make sure it's already drawn.
thank you
Tal

**Comment by stevenweaver** [comment]
Hello Tal,

While there is no callback functionality, you could potentially use `tree.update_layout` in conjunction with the `layout_handler` option in phylotree.js. 

Please view http://bl.ocks.org/stevenweaver/1c9c8e5c42560dee520685f056561ae2 for an example with your console window open. 

Best,
Steven

**Comment by talnagar** [comment]
Thank you!
