### ISSUE TITLE
Saving tree svg as png - branches appear as filled in black triangles 

### ISSUE THREAD

**Issue by hannah-fisher** [veg/phylotree.js#210]
Hi. 
I am displaying a phylotree in an svg on an html page. I am trying to add a feature which is a button that when clicked saves the tree as a png file. Things mostly seem to be working - the branches and nodes have the color style that I applied to them, so that is good. However, I am having one odd problem that I am pretty lost about how to fix. The branches, instead of appearing as lines, are appearing as filled in black triangles. 
Here is what the tree looks like when I download it: 
![image](https://user-images.githubusercontent.com/47338195/88084656-94e79200-cb39-11ea-9e2e-3325d7157433.png)

Vs here is what the tree looks like in my browser:
![image](https://user-images.githubusercontent.com/47338195/88084824-cf512f00-cb39-11ea-8b32-0660471c4c6c.png)

My method of getting the picture is to draw the svg onto an image, draw the image onto a canvas, then download the canvas. My code is here: https://github.com/hannah-fisher/FAVITESWebTools/blob/master/TreeN93-Distance/buttons.js#L235
And the actual site is here: https://hannah-fisher.github.io/FAVITESWebTools/TreeN93-Distance/

Any advice on how to make the branches appear normal would be much appreciated, thank you so much!

**Comment by stevenweaver** [comment]
Hi @hannah-fisher, 

To export SVG, you need to include the css in the file. 

An example of generalized way to do this can be found here https://github.com/veg/hyphy-vision/blob/e684bf2ed541743e6df1966c6c6994a0491f6f3e/src/datamonkey/datamonkey.js#L59.

Best,
Steven

**Comment by hannah-fisher** [comment]
Thank you!
