### ISSUE TITLE
get tree's updated data after changes made

### ISSUE THREAD

**Issue by lizaaminov** [veg/phylotree.js#22]
I'm using your great library In my app, and i need to perform changes on the tree, is there way getting the tree's data after the changes made? (i.e. "tree" method)

Thanks,
Liza

**Comment by spond** [comment]
Dear @lizaaminov,

Could you please clarify your use case? I don't quite understand what changes are being made and what type of data you need to retrieve. A specific example would be most useful.

Sergei

**Comment by stevenweaver** [comment]
Closing this issue for now, but please feel free to reopen if you are still experiencing issues.
