### ISSUE TITLE
g attribute transform error

### ISSUE THREAD

**Issue by lianyi** [veg/phylotree.js#28]
Got the "g attribute transform error" from the console and it seems to be the map polyfill issue where the translate coordinates was miscalculated for the initial state.  

the issue can be reproduced from the official demo.  

![issue](https://cloud.githubusercontent.com/assets/8431331/21266685/38a8aa58-c375-11e6-930a-3fb5ac0ebba0.png)
 
I think I found a fix and will send in a PR after confirm it's working.

**Comment by stevenweaver** [comment]
Resolved in `master` branch, and comments can be found in #29. Will be included in v1.0.5.
