### ISSUE TITLE
Clade space

### ISSUE THREAD

**Issue by machalita** [veg/phylotree.js#32]
Good afternoon! After modifying the style to make the clades invisible:
        .clade {
          fill :white;
          stroke :white;
        }
I'm still left with a huge empty space (after collapsing 100 nodes at the beggining of the tree), how can I control the space/size of the clades when collapsing?
![image](https://cloud.githubusercontent.com/assets/12822936/21668791/86d42ee0-d348-11e6-8500-65c8be171de1.png)

Thanks again!

**Comment by spond** [comment]
Dear @machalita,

You can "hide" entire clades using a different dropdown option:

![jan-05-2017 19-40-29](https://cloud.githubusercontent.com/assets/1018513/21708642/d31b0734-d37e-11e6-9125-1f4e1b91f495.gif)

The programmatic call to accomplish the same is as follows.

```
// hide all subtrees rooted at the nodes in the first argument, [node] in this example
phylotree.modify_selection([node], "notshown", true, true).update_has_hidden_nodes().update();

// show all hidden descendants of "node"
phylotree.modify_selection(phylotree.select_all_descendants(node, true, true), "notshown", true, true, "false").update_has_hidden_nodes().update();
```

Best,
Sergei
