### ISSUE TITLE
Combined example of phylotree.js and alignment.js?

### ISSUE THREAD

**Issue by santule** [veg/phylotree.js#416]
Hello,

I need to integrate the sequence information for each node in the tree. I tried doing this manually using rectangles and text as shown below. But it does not work too well.
<img width="1084" alt="Screen Shot 2022-04-27 at 4 54 42 pm" src="https://user-images.githubusercontent.com/20509836/165672183-dfbccc9f-66ca-4074-a460-45e8740ec2c6.png">

The alignment.js library would handle this better. Is there a basic example available for showing tree and alignment information besides each node of the tree?

Thanks.

**Comment by santule** [comment]
i will raise this in alignment.js library issue board. closing it from here.

**Comment by spond** [comment]
Dear @santule,

Sorry I have been busy with other projects to pay close attention to `phylotree.js` in the last couple of weeks. For this specific issue I would suggest using a <tt>a monospace font </tt> so that each letter has the same width and you can match the text and the boxes.

Best,
Sergei
