### ISSUE TITLE
I need a documentation 

### ISSUE THREAD

**Issue by pedrogiroldo** [veg/phylotree.js#436]
I'm thinking about use this library on my project, but i can't find an complete doc to learn how to use it.

**Comment by stevenweaver** [comment]
Dear @pedrogiroldo, 

Please take a look at this collection of examples for how to use it:
https://observablehq.com/collection/@stevenweaver/phylotree-utilities

Also, a complete API is available here:
https://github.com/veg/phylotree.js/blob/master/API.md

If you have any questions, please feel free to open issues as well. 


Best,
Steven

**Comment by pedrogiroldo** [comment]
That's great! Where can I find the rendering options and this kind of stuff?

**Comment by stevenweaver** [comment]
Dear @pedrogiroldo, 

Have a look at the Observable notebook cells. For items such as coloring nodes or branches (among other stylistic changes). 

For example, take a look at this one:
https://observablehq.com/@stevenweaver/phylotree-1-0-0-unscaled-iav-ha-colored-by-host?collection=@stevenweaver/phylotree-utilities

The `nodeColorizer` colorizes the nodes, and `edgeColorizer` for branches. 

Then the functions are set like so:

```
renderedTree = tree.render({
  height:height, 
  width:width,
  'left-right-spacing': 'fit-to-size', 
  'align-tips':true,
  'node-styler': colorNodesByName,
  'edge-styler': colorEdgesByTarget
});
```

The full list of options is in this part of the code, https://github.com/veg/phylotree.js/blob/master/src/render/draw.js#L61. It does appear that documentation does need to be updated to describe each one. I'll keep this issue open until that is completed.

Best,
Steven

**Comment by pedrogiroldo** [comment]
Thank you so much! I truly value your contributions to this project. If you require any assistance with updating the documentation, please don't hesitate to reach out. Your enthusiasm for this project is greatly appreciated!

**Comment by pedrogiroldo** [comment]
@stevenweaver, could you please explain how to display a tree in an HTML document and how to download the SVG?
