### ISSUE TITLE
Setting the font-size doesn't work

### ISSUE THREAD

**Issue by gaurav** [veg/phylotree.js#439]
All the options to `tree.render()` (e.g. "align-tips", "container", "width", "height") work correctly, but neither "font-size" or "font_size" changes the font size for the labels (which remains stuck at `12px`, which is really small -- are you sure you didn't mean `12pt`?). I was able to resize the text by adding a CSS instruction:

```
.phylotree-node-text {
  font-size: 12pt !important;
}
```

However, I'd like to know what the correct way of doing this is so I can use that instead.

**Comment by stevenweaver** [comment]
Dear @gaurav, 

You aren't the first that has reported this. Let me see if I can make node font size configurable. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @gaurav, 

Due to the way the code is written, supporting units other than `px` would take some time. Can you review the PR #443 and see if that meets your needs?

Best,
Steven

**Comment by gaurav** [comment]
Yup, that should be fine for now -- thanks for making this work!
