### ISSUE TITLE
D3 v4

### ISSUE THREAD

**Issue by thomasstjerne** [veg/phylotree.js#44]
This is a great project. Thanks!

Just a question: Do you have plans / thoughts about moving to D3 v4 ?
Seems that that D3 v4 introduced some breaking changes.

**Comment by stevenweaver** [comment]
Dear @thomasstjerne, 

We are actively moving to D3 v5. A quite usable version is in the v3-to-v5 branch. 

Best,
Steven

**Comment by thomasstjerne** [comment]
Thanks for these good news @stevenweaver

**Comment by sahithimacha** [comment]
@stevenweaver I have looked at this project when i am researching for one of my project requirements. its a very nice project for phylotree visualizations. Any update on D3 V5 migration? any tentative date on the release? is there any github project we can seewith D# v5?

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

I've ported over a version of phylotree to d3v5 that is quite usable.  It's in the [1.0.0-alpha](https://github.com/veg/phylotree.js/tree/1.0.0-alpha) branch. There are a few outstanding bugs, so we haven't officially released it quite yet.

The new version also works with node, so if you are developing phylogenetic algorithms, you can develop outside of the browser if you like. 

I have an example on how to use the new version [https://observablehq.com/@stevenweaver/phylotree-1-0-0](here). 

Best,
Steven

**Comment by sahithimacha** [comment]
@stevenweaver Awesome. i will try this version. Thank you so much.

**Comment by sahithimacha** [comment]
@stevenweaver i am using this in angular application.  i tried helloworld in example section in the previous branch it worked fine but it didn't support D3 V5. in this 1.00-alpha branch also helloword example is still using d3 v3. any plans on migrating these examples to work in D3 v5? or is there any other way i need to use these examples to work in d3 v5?

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

I've updated the hello-world example to show the use of d3v5 in commit e7664183828ab7901f77341c23041d8456e0e993. 

Best,
Steven

**Comment by sahithimacha** [comment]
@stevenweaver can i use this with the phylotree package install (npm install phylotree)?
Is there any way i can talk to you so that i can explain what i am trying to do?

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

Yes, `npm install phylotree@alpha` or `yarn add phylotree@alpha` should work. My availability is a bit spotty this week due to impending deadlines on a separate project I am on. If you tell me which example using phylotree would help you most, I can see what can be done. 

Best,
Steven

**Comment by sahithimacha** [comment]
@stevenweaver  Sure, i will try with phylotree@alpha and let you know. Thank you very much for your help. I have researched for a week but i couldn't find any phylotree librabry which supports D3 v5. so i have ended up asking you for the V5 release.

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

No problem. I am happy to hear there is demand! 

Best,
Steven

**Comment by sahithimacha** [comment]
i tried installing phylotree@alpha but getting errors.
![image](https://user-images.githubusercontent.com/39495675/57033807-826ef900-6c13-11e9-8421-7f2835397384.png)

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

Please ensure you are connected to the internet and that DNS is able to resolve registry.npmjs.org. You may want to contact your IT department.

Best,
Steven

**Comment by sahithimacha** [comment]
@stevenweaver thank you. I tried it at home and able to install the package. but i am not able to use this in my project. getting an error can't find the module phylotree.
![image](https://user-images.githubusercontent.com/39495675/57095717-21115d80-6cd9-11e9-96ba-99cd15e13b16.png)

**Comment by sahithimacha** [comment]
![image](https://user-images.githubusercontent.com/39495675/57095962-b6aced00-6cd9-11e9-8309-f9eee3b4580c.png)

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

Can you please make sure that your package.json looks like this:

```
  "dependencies": {
    "phylotree": "1.0.0-alpha.11"
  }
```

**Comment by sahithimacha** [comment]
@stevenweaver 
![image](https://user-images.githubusercontent.com/39495675/57097174-aba78c00-6cdc-11e9-8104-1df1dd2e960d.png)

I have v 1.0.0-alpha.10 in my package.json

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

The issue you're experiencing was resolved with this commit https://github.com/veg/phylotree.js/commit/dfea6d93e26c953086224ee0aa05d702e46310b8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2. 

It appears `1.0.0-alpha.11` wasn't tagged with `alpha` when published to `npm`. Can you update to `1.0.0-alpha.11`?

Apologies,
Steven

**Comment by sahithimacha** [comment]
@stevenweaver trying to install the package again.. but coundn't

![image](https://user-images.githubusercontent.com/39495675/57112516-f5f13300-6d05-11e9-820f-045aecdc0c90.png)

**Comment by sahithimacha** [comment]
@stevenweaver trying to install package but couldn't

![image](https://user-images.githubusercontent.com/39495675/57112548-220cb400-6d06-11e9-9a39-03d409df1963.png)

**Comment by sahithimacha** [comment]
@stevenweaver tried installing again but its still adding alpha.10 anly

![image](https://user-images.githubusercontent.com/39495675/57112732-ed4d2c80-6d06-11e9-9759-be48751adce7.png)

**Comment by sahithimacha** [comment]
@stevenweaver it is with npm install phylotree@alpha only right? or with any other version install? i tried again but still it is adding alpha.10 only. how can i update to alpha.11?

**Comment by stephenshank** [comment]
Dear @sahithimacha,

Thanks for your interest in the alpha version of phylotree! Please try `npm install phylotree.js@1.0.0-alpha.12`, and do let us know how it goes.

Best,
Stephen

**Comment by sahithimacha** [comment]
stephenshank It worked. Thank you very much. Tried the hello world example. looks like the representation of branches changed. I mean the tree view. Is there any way we can get the view exactly like in version 1?
![image](https://user-images.githubusercontent.com/39495675/57241651-14ea1080-6ff7-11e9-8a7f-90f70af09b79.png)

**Comment by spond** [comment]
Dear @sahithimacha,

You need to include the appropriate CSS files, e.g. 

```
<link rel=stylesheet href='https://unpkg.com/phylotree@0.1/phylotree.css'>
```

Best,
Sergei

**Comment by sahithimacha** [comment]
Awesome. It's working as expected. I thought the css also included with the package. will explore the other examples and let you know. Thank you so much.

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

We had to modernize the phyloxml example a bit for you. Go ahead and give `1.0.0-alpha.13` a go, and view the example at in `examples/phyloxml/index.html`.

Best,
Steven

**Comment by sahithimacha** [comment]
@stevenweaver Thank you very much. I tried 1.0.0-alpha.13 but its giving the error.

![image](https://user-images.githubusercontent.com/39495675/57265165-db87c400-703b-11e9-8d26-6ef394d1aa13.png)

**Comment by stevenweaver** [comment]
Dear @sahithimacha,

The perils of being on the bleeding edge.

Please try:

npm install phylotree@1.0.0-alpha.14


Best,

Steven

**Comment by sahithimacha** [comment]
@stevenweaver No errors. package installed. Will try the example and let you know. Thank you

**Comment by sahithimacha** [comment]
@stevenweaver example also working. Thank you so much. I will try using this package in our application with real data.

**Comment by stevenweaver** [comment]
Dear @sahithimacha, 

I'm glad to hear it! The port to `v5` took some effort, so I'm glad to see that it is already being appreciated!

Best,
Steven

**Comment by sahithimacha** [comment]
@stevenweaver  in our application the data i need show is in the below format.
![image](https://user-images.githubusercontent.com/39495675/57321617-577b1e00-70c7-11e9-9ba6-feb23ebf7bb5.png)

so i am playing with phyloxml example to show the branch and name colors. when i did this in the script i will be able to display the branch colors.
rendered_tree.style_edges (function (element, data: any) {
      console.log(data);
        if (data.target.data.name == "A" || data.target.data.name == "B") {
          element.style ("stroke", "red");
        }
        if (data.target.data.name == "C" || data.target.data.name == "D") {
          element.style ("stroke", "blue");
        }
    });

but instead of that, is there any way we can include the <color> tag in the xml for name and branch and display the output accordingly.

Any suggestions?

**Comment by stephenshank** [comment]
Dear @sahithimacha,

In `examples/phyloxml/index.html`, I added `tree.get_node_by_name('Octopus vulgaris')` right before this object goes out of scope in the script tag. The corresponding entry in the phyloxml file is

![image](https://user-images.githubusercontent.com/8673708/57380878-d334a380-7177-11e9-9a9f-96f6f03c8a36.png)

and you'll see this information is indeed exposed in the data field of the node object:

![image](https://user-images.githubusercontent.com/8673708/57381036-2c043c00-7178-11e9-9024-49879552420c.png)

So it should be possible to write the appropriate functions to leverage any XML information. Note that it automatically reads `taxonomy.scientific_name` for the name, and `branch_length` for the branch length, as seen in [these lines](https://github.com/veg/phylotree.js/blob/1.0.0-alpha/src/formats/phyloxml.js#L58-L63).

If this isn't sufficient, I'd need more information about the format of your phyloxml file, and exactly what you're trying to do.

We're glad to help you utilize phylotree.js in your own work! If you have additional questions, feel free to open up a dedicated issue (i.e., "Using phyloxml data for aesthetics"). This is for the benefit of future users who may be searching for the same issue.

Best,
Stephen

**Comment by MortenHofft** [comment]
Wonderful to hear that you are working to bring it up to d3v5. thank you.

> All my observables use phylotree 1.0.0.

The examples are not working at the moment. I just see `tree = RuntimeError: phylotree could not be resolved`

**Comment by stevenweaver** [comment]
Dear @MortenHofft, 

Apologies. A `node.js` only package managed to slip into our dependency tree. The notebooks should now work as advertised.

@stephenshank - I've moved the slatkin-maddision implementation into a new branch until it supports both the browser and node. 

Best,
Steven
