### ISSUE TITLE
Root internal node label is overwritten with "root"

### ISSUE THREAD

**Issue by gaurav** [veg/phylotree.js#60]
I wanted to display internal labels (just like #56), so I [wrote a custom node styler](https://github.com/phyloref/curation-tool/blob/7ab096888615b99fa50570734d45ddd9cb81072c/js/curation-tool.js#L567-L599). This works fine for internal nodes anywhere in the phylogeny *except* at the root, where the node is always relabeled "root" when loading from Newick. I could come up with a workaround at my end, but I wondered if it might be relatively easy to fix in Phylotree.js by using some other method to flag the root node. I might be able to spend a bit of time working on that bug for work and sending you a pull request if that might be helpful.

Thank you for writing just a great library!

**Comment by spond** [comment]
Dear @gaurav,

Thank you for pointing this out. The Newick parser was not correctly handling optional root node names. I fixed that issue (I think) with eb36c6f, please confirm that it resolves your issue.

Best,
Sergei

**Comment by gaurav** [comment]
Thank you so much, Sergei! I haven't had a chance to test it yet -- I very lazily load your code directly from veg.github.io rather than from a local copy -- but I'll do so in the next day or two and report back!

**Comment by gaurav** [comment]
Okay, I finally got a chance to test it -- thank you so much for your help! It looks like there's one minor issue: Newick files can end with semicolons (see [some examples from Wikipedia](https://en.wikipedia.org/wiki/Newick_format#Examples)), and phylotree.js now parses the semicolon as part of the root node -- so, for `(A,(B, C))D;`, it thinks the root node is labeled "D;", not "D". Should I file a separate issue for that?

**Comment by spond** [comment]
Dear @gaurav,

No need to make a separate issue, I will keep this open until I issue a fix. Thanks for noticing and reporting.

Best,
Sergei

**Comment by gaurav** [comment]
Thank you so much for these fixes!
