### ISSUE TITLE
Add method for exporting the Newick string with internal node labels

### ISSUE THREAD

**Issue by gaurav** [veg/phylotree.js#61]
[`get_newick`](https://github.com/veg/phylotree.js/blob/eb36c6f6e3fe00f1e3d6562203b129335b988762/phylotree.js#L1056-L1063) defaults to returning only terminal labels. I think it would be useful to have a second method, [`get_newick_with_internal_labels`](https://github.com/phyloref/curation-tool/pull/33/commits/9f908f6bfe0b00b1e9e40527ac23aee25779a909#diff-cd47ea0dbb7a63eb7e6781b134b9a8e0R1009), that would default to including internal labels as well.

**Comment by spond** [comment]
Dear @gaurav,

You should already be able to do it in 3 different ways

1. Specify `"internal-names" : true` in `options` when you create the tree object. This will draw internal node labels in the tree and show them in the exported string.

2. Supply your own callback to `phylotree.branch_name`, which will return something for internal nodes (the default is to return "")

3. Provide an annotator function as an argument `get_newick`. It is a callback that takes a node as its argument and returns the string to paste after the default node name. If this function returns nothing for leaves, and the node name for internal nodes, you should achieve the desired effect.

Best,
Sergei

**Comment by gaurav** [comment]
Thanks so much! Using the "internal-names" option works perfectly.
