### ISSUE TITLE
Root-to-tip

### ISSUE THREAD

**Issue by spond** [veg/phylotree.js#66]
Dear @stephenshank,

We should prettify this code example https://bl.ocks.org/spond/raw/c827d8c2f68cf1daa762/ which computes root-to-tip linear regression on fixed trees. Would be a useful standalone app, especially since you can also interactively see what changing the root does.

Brittany would be a good point person to ask for feedback.

Best,
Sergei

**Comment by stevenweaver** [comment]
Note - I think we're moving over to ObservableHQ from blocks now. An example of root-to-tip linear regression can be found here. 

https://beta.observablehq.com/@stevenweaver/computing-root-to-tip-distances-with-phylotree-js
