### ISSUE TITLE
phylotree not displaying

### ISSUE THREAD

**Issue by ramaniritika** [veg/phylotree.js#70]
I am using phylotree.js on my website and it has been working without any issues till 4-5 days ago. The tree wont display on my end even though it works on the demo website. 
Here is a link to the website - http://compgen.cshl.edu/phastweb/phyloexample.php

**Comment by spond** [comment]
Dear @ramaniritika,

Did you resolve the issue?

Best,
Sergei

**Comment by ramaniritika** [comment]
Hello, yes, the link to the d3 library was broken.

Thanks!
Ritika
