### ISSUE TITLE
Don't show menus if there are no items

### ISSUE THREAD

**Issue by rambaut** [veg/phylotree.js#76]
If there are no items left in a menu (because rooting and hiding have been disabled) then it would be better not to show a menu than an empty one.

**Comment by rambaut** [comment]
It might also be useful to be able to switch node menus on and off independent of this.

**Comment by stephenshank** [comment]
Dear @rambaut,

The above pull request (#81) addresses this issue. Thanks for reporting!

Best,
Stephen
