### ISSUE TITLE
need a way to scale bubble sizes

### ISSUE THREAD

**Issue by kemaleren** [veg/phylotree.js#8]
Leaf nodes with large copy numbers get huge bubbles. I have attempted a fix in this commit: kemaleren/phylotree.js@947d5cf192bfa36dce40f84d8d97f216b30eee4c. Not submitting a pull request yet, because changing `relative_node_span` changes the extent. For some reason, it is making the trees much wider than before.

Here is an example of the problem. The tree has a node with a copy number of 7,757.
![huge-bubble-size](https://cloud.githubusercontent.com/assets/694043/9969345/d66c2abe-5e02-11e5-98f1-407cdb0710e9.png)

And the same tree in radial layout:
![radial-bubbles](https://cloud.githubusercontent.com/assets/694043/9969346/d67ee6ae-5e02-11e5-97af-49a4b825f90f.png)

**Comment by spond** [comment]
Hi kemal,

You should be able to do this:

```
tree.node_span(function (data) { // data is the node itself
    ... do stuff ...
     return node_size;
});
```

Sergei

**Comment by kemaleren** [comment]
Ah, that makes sense. Don't know why I didn't notice that earlier.
