### ISSUE TITLE
Contributing.md?

### ISSUE THREAD

**Issue by ArtPoon** [veg/phylotree.js#97]
I'm trying to package a local copy of this repo so that I can start doing some customization, but I've been unable to do so with `yarn run develop`.  First, installing `yarn` is broken in Ubuntu 18.04 (similar to [this issue](https://github.com/yarnpkg/yarn/issues/3189)), so I did a local install of release `1.11`.  Next, running this command yielded the following:
```
yarn run v1.11.1
$ concurrently "webpack --watch --mode=development" "http-server"
/bin/sh: 1: concurrently: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Is there a specific version of `yarn` I should be using, and can you please list any other dependencies for development?

**Comment by rdvelazquez** [comment]
I think the dependencies need to be installed first either with yarn or npm. With yarn simply use the command `yarn`, with npm use `npm install`. `concurrently` is a dependency (hence the error). If you can confirm that this works I'll update the readme.

**Comment by stevenweaver** [comment]
Dear @ArtPoon, 

Putting together a CONTRIBUTING.md is definitely something worthwhile. I'll put one together today and reference this issue once completed. 

Best,
Steven

**Comment by ArtPoon** [comment]
Ok, this sequence on a fairly bare-bones Ubuntu 18.04 system seemed to work as far as pulling in dependencies:
* sudo apt install npm
* npm install
but I'm clueless about the "build" process to generate `phylotree.js`, which looks like a minified file.

**Comment by ArtPoon** [comment]
Current attempt:
* `sudo npm install -g npx`
* `npx webpack --config webpack.config.js`
  produces this error:
  ```
  Cannot read property 'properties' of undefined
  ```

**Comment by stevenweaver** [comment]
Dear @ArtPoon, 

Apologies, I found myself in more meetings than anticipated this afternoon. The following sequence of commands work for me. 

```
git clone git@github.com:veg/phylotree.js phylo
npm install -g yarn
yarn global add webpack-cli
webpack
```

The versions that I'm currently using 
```
17:34:43 sweaver@sweaver-imac phylo master ? webpack --version                                                                                                                                                                                                                                                                                                                                                                                                                     130 ↵
4.20.2
17:34:49 sweaver@ phylo master ? node --version
v9.11.2
```

The JavaScript ecosystem is fast moving, so what is in Linux repositories can be out-of-date. Once the CONTRIBUTING guide is written, I'm hoping that it will alleviate some of the environment issues you've come across. 


Best,
Steven

**Comment by ArtPoon** [comment]
Much appreciated!  I’ll give it a whirl tonight.
